# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # managing dependencies for composer
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "07:00"
      timezone: "Asia/Bangkok"
    allow:
      - dependency-type: "production"
      - dependency-type: "development"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999

    # managing dependencies for node/npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "07:00"
      timezone: "Asia/Bangkok"
    allow:
      - dependency-type: "production"
      - dependency-type: "development"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
